const FOOD_DATA = [
  {
    "name":"Burger",
    "brand":"Homemade",
    "image":"burger.png"
     },
  {
    "name":"noodle",
    "brand":"Homemade",
    "image":"noodle.png"
  },
  {
    "name":"Pasta",
    "brand":"Homemade",
    "image":"pasta.png"
  },
  {
    "name":"Tsuivan",
    "brand":"Homemade",
    "image":"tsui.jpg"
  },
  {
    "name":"Chicken",
    "brand":"Homemade",
    "image":"pasta.png"
  },
  {
    "name":"Noodles",
    "brand":"Homemade",
    "image":"noodle.png"
  },
  {
    "name":"Pizza",
    "brand":"Homemade",
    "image":"pasta.png"
  },
  {
    "name":"Sandwich",
    "brand":"Homemade",
    "image":"noodle.png"
  },

];